/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps, @typescript-eslint/no-unused-vars */
import React, { useState } from 'react';
import Select from 'react-select';
import styles from './styles.module.css';

interface CodesCiiuProps {
    onSelect: (codeCiiu: string) => void;
}

const CodesCiiu: React.FC<CodesCiiuProps> = ({ onSelect }) => {
    const [ codeCiiu, setCiiuCode ] = useState<{ value: string; label: string } | null>(null);

    const handleCiiuCodeChange = (selectedOption: any) => {
        setCiiuCode(selectedOption);
        onSelect(selectedOption.value);
    };

    const codesCiiu: { value: string; label: string }[] = [
        { value: "0111", label: "0111 - Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas" },
        { value: "0112", label: "0112 - Cultivo de arroz" },
        { value: "0113", label: "0113 - Cultivo de hortalizas, raíces y tubérculos" },
        { value: "0114", label: "0114 - Cultivo de tabaco" },
        { value: "0115", label: "0115 - Cultivo de plantas textiles" },
        { value: "0119", label: "0119 - Otros cultivos transitorios n.c.p." },
        { value: "0121", label: "0121 - Cultivo de frutas tropicales y subtropicales" },
        { value: "0122", label: "0122 - Cultivo de plátano y banano" },
        { value: "0123", label: "0123 - Cultivo de café" },
        { value: "0124", label: "0124 - Cultivo de caña de azúcar" },
        { value: "0125", label: "0125 - Cultivo de flor de corte" },
        { value: "0126", label: "0126 - Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos" },
        { value: "0127", label: "0127 - Cultivo de plantas con las que se preparan bebidas" },
        { value: "0128", label: "0128 - Cultivo de especias y de plantas aromáticas y medicinales" },
        { value: "0129", label: "0129 - Otros cultivos permanentes n.c.p." },
        { value: "0130", label: "0130 - Propagación de plantas (actividades de los viveros, excepto viveros forestales)" },
        { value: "0141", label: "0141 - Cría de ganado bovino y bufalino" },
        { value: "0142", label: "0142 - Cría de caballos y otros equinos" },
        { value: "0143", label: "0143 - Cría de ovejas y cabras" },
        { value: "0144", label: "0144 - Cría de ganado porcino" },
        { value: "0145", label: "0145 - Cría de aves de corral" },
        { value: "0149", label: "0149 - Cría de otros animales n.c.p." },
        { value: "0150", label: "0150 - Explotación mixta (agrícola y pecuaria)" },
        { value: "0161", label: "0161 - Actividades de apoyo a la agricultura" },
        { value: "0162", label: "0162 - Actividades de apoyo a la ganadería" },
        { value: "0163", label: "0163 - Actividades posteriores a la cosecha" },
        { value: "0164", label: "0164 - Tratamiento de semillas para propagación" },
        { value: "0170", label: "0170 - Caza ordinaria y mediante trampas y actividades de servicios conexas" },
        { value: "0210", label: "0210 - Silvicultura y otras actividades forestales" },
        { value: "0220", label: "0220 - Extracción de madera" },
        { value: "0230", label: "0230 - Recolección de productos forestales diferentes a la madera" },
        { value: "0240", label: "0240 - Servicios de apoyo a la silvicultura" },
        { value: "0311", label: "0311 - Pesca marítima" },
        { value: "0312", label: "0312 - Pesca de agua dulce" },
        { value: "0321", label: "0321 - Acuicultura marítima" },
        { value: "0322", label: "0322 - Acuicultura de agua dulce" },
        { value: "0510", label: "0510 - Extracción de hulla (carbón de piedra)" },
        { value: "0520", label: "0520 - Extracción de carbón lignito" },
        { value: "0610", label: "0610 - Extracción de petróleo crudo" },
        { value: "0620", label: "0620 - Extracción de gas natural" },
        { value: "0710", label: "0710 - Extracción de minerales de hierro" },
        { value: "0721", label: "0721 - Extracción de minerales de uranio y de torio" },
        { value: "0722", label: "0722 - Extracción de oro y otros metales preciosos" },
        { value: "0723", label: "0723 - Extracción de minerales de níquel" },
        { value: "0729", label: "0729 - Extracción de otros minerales metalíferos no ferrosos n.c.p." },
        { value: "0811", label: "0811 - Extracción de piedra, arena, arcillas comunes, yeso y anhidrita" },
        { value: "0812", label: "0812 - Extracción de arcillas de uso industrial, caliza, caolín y bentonitas" },
        { value: "0820", label: "0820 - Extracción de esmeraldas, piedras preciosas y semipreciosas" },
        { value: "0891", label: "0891 - Extracción de minerales para la fabricación de abonos y productos químicos" },
        { value: "0892", label: "0892 - Extracción de halita (sal)" },
        { value: "0899", label: "0899 - Extracción de otros minerales no metálicos n.c.p." },
        { value: "0910", label: "0910 - Actividades de apoyo para la extracción de petróleo y de gas natural" },
        { value: "0990", label: "0990 - Actividades de apoyo para otras actividades de explotación de minas y canteras" },
        { value: "1011", label: "1011 - Procesamiento y conservación de carne y productos cárnicos" },
        { value: "1012", label: "1012 - Procesamiento y conservación de pescados, crustáceos y moluscos" },
        { value: "1020", label: "1020 - Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos" },
        { value: "1030", label: "1030 - Elaboración de aceites y grasas de origen vegetal y animal" },
        { value: "1040", label: "1040 - Elaboración de productos lácteos" },
        { value: "1051", label: "1051 - Elaboración de productos de molinería" },
        { value: "1052", label: "1052 - Elaboración de almidones y productos derivados del almidón" },
        { value: "1061", label: "1061 - Trilla de café" },
        { value: "1062", label: "1062 - Descafeinado, tostión y molienda del café" },
        { value: "1063", label: "1063 - Otros derivados del café" },
        { value: "1071", label: "1071 - Elaboración y refinación de azúcar" },
        { value: "1072", label: "1072 - Elaboración de panela" },
        { value: "1081", label: "1081 - Elaboración de productos de panadería" },
        { value: "1082", label: "1082 - Elaboración de cacao, chocolate y productos de confitería" },
        { value: "1083", label: "1083 - Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares" },
        { value: "1084", label: "1084 - Elaboración de comidas y platos preparados" },
        { value: "1089", label: "1089 - Elaboración de otros productos alimenticios n.c.p." },
        { value: "1090", label: "1090 - Elaboración de alimentos preparados para animales" },
        { value: "1101", label: "1101 - Destilación, rectificación y mezcla de bebidas alcohólicas" },
        { value: "1102", label: "1102 - Elaboración de bebidas fermentadas no destiladas" },
        { value: "1103", label: "1103 - Producción de malta, elaboración de cervezas y otras bebidas malteadas" },
        { value: "1104", label: "1104 - Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas" },
        { value: "1200", label: "1200 - Elaboración de productos de tabaco" },
        { value: "1311", label: "1311 - Preparación e hilatura de fibras textiles" },
        { value: "1312", label: "1312 - Tejeduría de productos textiles" },
        { value: "1313", label: "1313 - Acabado de productos textiles" },
        { value: "1391", label: "1391 - Fabricación de tejidos de punto y ganchillo" },
        { value: "1392", label: "1392 - Confección de artículos con materiales textiles, excepto prendas de vestir" },
        { value: "1393", label: "1393 - Fabricación de tapetes y alfombras para pisos" },
        { value: "1394", label: "1394 - Fabricación de cuerdas, cordeles, cables, bramantes y redes" },
        { value: "1399", label: "1399 - Fabricación de otros artículos textiles n.c.p." },
        { value: "1410", label: "1410 - Confección de prendas de vestir, excepto prendas de piel" },
        { value: "1420", label: "1420 - Fabricación de artículos de piel" },
        { value: "1430", label: "1430 - Fabricación de artículos de punto y ganchillo" },
        { value: "1511", label: "1511 - Curtido y recurtido de cueros; recurtido y teñido de pieles" },
        { value: "1512", label: "1512 - Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería" },
        { value: "1513", label: "1513 - Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales" },
        { value: "1521", label: "1521 - Fabricación de calzado de cuero y piel, con cualquier tipo de suela" },
        { value: "1522", label: "1522 - Fabricación de otros tipos de calzado, excepto calzado de cuero y piel" },
        { value: "1523", label: "1523 - Fabricación de partes del calzado" },
        { value: "1610", label: "1610 - Aserrado, acepillado e impregnación de la madera" },
        { value: "1620", label: "1620 - Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles" },
        { value: "1630", label: "1630 - Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción" },
        { value: "1640", label: "1640 - Fabricación de recipientes de madera" },
        { value: "1690", label: "1690 - Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería" },
        { value: "1701", label: "1701 - Fabricación de pulpas (pastas) celulósicas; papel y cartón" },
        { value: "1702", label: "1702 - Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón." },
        { value: "1709", label: "1709 - Fabricación de otros artículos de papel y cartón" },
        { value: "1811", label: "1811 - Actividades de impresión" },
        { value: "1812", label: "1812 - Actividades de servicios relacionados con la impresión" },
        { value: "1820", label: "1820 - Producción de copias a partir de grabaciones originales" },
        { value: "1910", label: "1910 - Fabricación de productos de hornos de coque" },
        { value: "1921", label: "1921 - Fabricación de productos de la refinación del petróleo" },
        { value: "1922", label: "1922 - Actividad de mezcla de combustibles" },
        { value: "2011", label: "2011 - Fabricación de sustancias y productos químicos básicos" },
        { value: "2012", label: "2012 - Fabricación de abonos y compuestos inorgánicos nitrogenados" },
        { value: "2013", label: "2013 - Fabricación de plásticos en formas primarias" },
        { value: "2014", label: "2014 - Fabricación de caucho sintético en formas primarias" },
        { value: "2021", label: "2021 - Fabricación de plaguicidas y otros productos químicos de uso agropecuario" },
        { value: "2022", label: "2022 - Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas" },
        { value: "2023", label: "2023 - Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador" },
        { value: "2029", label: "2029 - Fabricación de otros productos químicos n.c.p." },
        { value: "2030", label: "2030 - Fabricación de fibras sintéticas y artificiales" },
        { value: "2100", label: "2100 - Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico" },
        { value: "2211", label: "2211 - Fabricación de llantas y neumáticos de caucho" },
        { value: "2212", label: "2212 - Reencauche de llantas usadas" },
        { value: "2219", label: "2219 - Fabricación de formas básicas de caucho y otros productos de caucho n.c.p." },
        { value: "2221", label: "2221 - Fabricación de formas básicas de plástico" },
        { value: "2229", label: "2229 - Fabricación de artículos de plástico n.c.p." },
        { value: "2310", label: "2310 - Fabricación de vidrio y productos de vidrio" },
        { value: "2391", label: "2391 - Fabricación de productos refractarios" },
        { value: "2392", label: "2392 - Fabricación de materiales de arcilla para la construcción" },
        { value: "2393", label: "2393 - Fabricación de otros productos de cerámica y porcelana" },
        { value: "2394", label: "2394 - Fabricación de cemento, cal y yeso" },
        { value: "2395", label: "2395 - Fabricación de artículos de hormigón, cemento y yeso" },
        { value: "2396", label: "2396 - Corte, tallado y acabado de la piedra" },
        { value: "2399", label: "2399 - Fabricación de otros productos minerales no metálicos n.c.p." },
        { value: "2410", label: "2410 - Industrias básicas de hierro y de acero" },
        { value: "2421", label: "2421 - Industrias básicas de metales preciosos" },
        { value: "2429", label: "2429 - Industrias básicas de otros metales no ferrosos" },
        { value: "2431", label: "2431 - Fundición de hierro y de acero" },
        { value: "2432", label: "2432 - Fundición de metales no ferrosos" },
        { value: "2511", label: "2511 - Fabricación de productos metálicos para uso estructural" },
        { value: "2512", label: "2512 - Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías" },
        { value: "2513", label: "2513 - Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central" },
        { value: "2520", label: "2520 - Fabricación de armas y municiones" },
        { value: "2591", label: "2591 - Forja, prensado, estampado y laminado de metal; pulvimetalurgia" },
        { value: "2592", label: "2592 - Tratamiento y revestimiento de metales; mecanizado" },
        { value: "2593", label: "2593 - Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería" },
        { value: "2599", label: "2599 - Fabricación de otros productos elaborados de metal n.c.p." },
        { value: "2610", label: "2610 - Fabricación de componentes y tableros electrónicos" },
        { value: "2620", label: "2620 - Fabricación de computadoras y de equipo periférico" },
        { value: "2630", label: "2630 - Fabricación de equipos de comunicación" },
        { value: "2640", label: "2640 - Fabricación de aparatos electrónicos de consumo" },
        { value: "2651", label: "2651 - Fabricación de equipo de medición, prueba, navegación y control" },
        { value: "2652", label: "2652 - Fabricación de relojes" },
        { value: "2660", label: "2660 - Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico" },
        { value: "2670", label: "2670 - Fabricación de instrumentos ópticos y equipo fotográfico" },
        { value: "2680", label: "2680 - Fabricación de medios magnéticos y ópticos para almacenamiento de datos" },
        { value: "2711", label: "2711 - Fabricación de motores, generadores y transformadores eléctricos" },
        { value: "2712", label: "2712 - Fabricación de aparatos de distribución y control de la energía eléctrica" },
        { value: "2720", label: "2720 - Fabricación de pilas, baterías y acumuladores eléctricos" },
        { value: "2731", label: "2731 - Fabricación de hilos y cables eléctricos y de fibra óptica" },
        { value: "2732", label: "2732 - Fabricación de dispositivos de cableado" },
        { value: "2740", label: "2740 - Fabricación de equipos eléctricos de iluminación" },
        { value: "2750", label: "2750 - Fabricación de aparatos de uso doméstico" },
        { value: "2790", label: "2790 - Fabricación de otros tipos de equipo eléctrico n.c.p." },
        { value: "2811", label: "2811 - Fabricación de motores, turbinas, y partes para motores de combustión interna" },
        { value: "2812", label: "2812 - Fabricación de equipos de potencia hidráulica y neumática" },
        { value: "2813", label: "2813 - Fabricación de otras bombas, compresores, grifos y válvulas" },
        { value: "2814", label: "2814 - Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión" },
        { value: "2815", label: "2815 - Fabricación de hornos, hogares y quemadores industriales" },
        { value: "2816", label: "2816 - Fabricación de equipo de elevación y manipulación" },
        { value: "2817", label: "2817 - Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)" },
        { value: "2818", label: "2818 - Fabricación de herramientas manuales con motor" },
        { value: "2819", label: "2819 - Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p." },
        { value: "2821", label: "2821 - Fabricación de maquinaria agropecuaria y forestal" },
        { value: "2822", label: "2822 - Fabricación de máquinas formadoras de metal y de máquinas herramienta" },
        { value: "2823", label: "2823 - Fabricación de maquinaria para la metalurgia" },
        { value: "2824", label: "2824 - Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción" },
        { value: "2825", label: "2825 - Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco" },
        { value: "2826", label: "2826 - Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros" },
        { value: "2829", label: "2829 - Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p." },
        { value: "2910", label: "2910 - Fabricación de vehículos automotores y sus motores" },
        { value: "2920", label: "2920 - Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques" },
        { value: "2930", label: "2930 - Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores" },
        { value: "3011", label: "3011 - Construcción de barcos y de estructuras flotantes" },
        { value: "3012", label: "3012 - Construcción de embarcaciones de recreo y deporte" },
        { value: "3020", label: "3020 - Fabricación de locomotoras y de material rodante para ferrocarriles" },
        { value: "3030", label: "3030 - Fabricación de aeronaves, naves espaciales y de maquinaria conexa" },
        { value: "3040", label: "3040 - Fabricación de vehículos militares de combate" },
        { value: "3091", label: "3091 - Fabricación de motocicletas" },
        { value: "3092", label: "3092 - Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad" },
        { value: "3099", label: "3099 - Fabricación de otros tipos de equipo de transporte n.c.p." },
        { value: "3110", label: "3110 - Fabricación de muebles" },
        { value: "3120", label: "3120 - Fabricación de colchones y somieres" },
        { value: "3210", label: "3210 - Fabricación de joyas, bisutería y artículos conexos" },
        { value: "3220", label: "3220 - Fabricación de instrumentos musicales" },
        { value: "3230", label: "3230 - Fabricación de artículos y equipo para la práctica del deporte" },
        { value: "3240", label: "3240 - Fabricación de juegos, juguetes y rompecabezas" },
        { value: "3250", label: "3250 - Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)" },
        { value: "3290", label: "3290 - Otras industrias manufactureras n.c.p." },
        { value: "3311", label: "3311 - Mantenimiento y reparación especializado de productos elaborados en metal" },
        { value: "3312", label: "3312 - Mantenimiento y reparación especializado de maquinaria y equipo" },
        { value: "3313", label: "3313 - Mantenimiento y reparación especializado de equipo electrónico y óptico" },
        { value: "3314", label: "3314 - Mantenimiento y reparación especializado de equipo eléctrico" },
        { value: "3315", label: "3315 - Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas" },
        { value: "3319", label: "3319 - Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p." },
        { value: "3320", label: "3320 - Instalación especializada de maquinaria y equipo industrial" },
        { value: "3511", label: "3511 - Generación de energía eléctrica" },
        { value: "3512", label: "3512 - Transmisión de energía eléctrica" },
        { value: "3513", label: "3513 - Distribución de energía eléctrica" },
        { value: "3514", label: "3514 - Comercialización de energía eléctrica" },
        { value: "3520", label: "3520 - Producción de gas; distribución de combustibles gaseosos por tuberías" },
        { value: "3530", label: "3530 - Suministro de vapor y aire acondicionado" },
        { value: "3600", label: "3600 - Captación, tratamiento y distribución de agua" },
        { value: "3700", label: "3700 - Evacuación y tratamiento de aguas residuales" },
        { value: "3811", label: "3811 - Recolección de desechos no peligrosos" },
        { value: "3812", label: "3812 - Recolección de desechos peligrosos" },
        { value: "3821", label: "3821 - Tratamiento y disposición de desechos no peligrosos" },
        { value: "3822", label: "3822 - Tratamiento y disposición de desechos peligrosos" },
        { value: "3830", label: "3830 - Recuperación de materiales" },
        { value: "3900", label: "3900 - Actividades de saneamiento ambiental y otros servicios de gestión de desechos" },
        { value: "4111", label: "4111 - Construcción de edificios residenciales" },
        { value: "4112", label: "4112 - Construcción de edificios no residenciales" },
        { value: "4210", label: "4210 - Construcción de carreteras y vías de ferrocarril" },
        { value: "4220", label: "4220 - Construcción de proyectos de servicio público" },
        { value: "4290", label: "4290 - Construcción de otras obras de ingeniería civil" },
        { value: "4311", label: "4311 - Demolición" },
        { value: "4312", label: "4312 - Preparación del terreno" },
        { value: "4321", label: "4321 - Instalaciones eléctricas" },
        { value: "4322", label: "4322 - Instalaciones de fontanería, calefacción y aire acondicionado" },
        { value: "4329", label: "4329 - Otras instalaciones especializadas" },
        { value: "4330", label: "4330 - Terminación y acabado de edificios y obras de ingeniería civil" },
        { value: "4390", label: "4390 - Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil" },
        { value: "4511", label: "4511 - Comercio de vehículos automotores nuevos" },
        { value: "4512", label: "4512 - Comercio de vehículos automotores usados" },
        { value: "4520", label: "4520 - Mantenimiento y reparación de vehículos automotores" },
        { value: "4530", label: "4530 - Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores" },
        { value: "4541", label: "4541 - Comercio de motocicletas y de sus partes, piezas y accesorios" },
        { value: "4542", label: "4542 - Mantenimiento y reparación de motocicletas y de sus partes y piezas" },
        { value: "4610", label: "4610 - Comercio al por mayor a cambio de una retribución o por contrata" },
        { value: "4620", label: "4620 - Comercio al por mayor de materias primas agropecuarias; animales vivos" },
        { value: "4631", label: "4631 - Comercio al por mayor de productos alimenticios" },
        { value: "4632", label: "4632 - Comercio al por mayor de bebidas y tabaco" },
        { value: "4641", label: "4641 - Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico" },
        { value: "4642", label: "4642 - Comercio al por mayor de prendas de vestir" },
        { value: "4643", label: "4643 - Comercio al por mayor de calzado" },
        { value: "4644", label: "4644 - Comercio al por mayor de aparatos y equipo de uso doméstico" },
        { value: "4645", label: "4645 - Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador" },
        { value: "4649", label: "4649 - Comercio al por mayor de otros utensilios domésticos n.c.p." },
        { value: "4651", label: "4651 - Comercio al por mayor de computadores, equipo periférico y programas de informática" },
        { value: "4651", label: "4651 - Comercio al por mayor de computadores, equipo periférico y programas de informática" },
        { value: "4652", label: "4652 - Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones" },
        { value: "4653", label: "4653 - Comercio al por mayor de maquinaria y equipo agropecuarios" },
        { value: "4659", label: "4659 - Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p." },
        { value: "4661", label: "4661 - Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos" },
        { value: "4662", label: "4662 - Comercio al por mayor de metales y productos metalíferos" },
        { value: "4663", label: "4663 - Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción" },
        { value: "4664", label: "4664 - Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario" },
        { value: "4665", label: "4665 - Comercio al por mayor de desperdicios, desechos y chatarra" },
        { value: "4669", label: "4669 - Comercio al por mayor de otros productos n.c.p." },
        { value: "4690", label: "4690 - Comercio al por mayor no especializado" },
        { value: "4711", label: "4711 - Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco" },
        { value: "4719", label: "4719 - Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco" },
        { value: "4721", label: "4721 - Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados" },
        { value: "4722", label: "4722 - Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados" },
        { value: "4723", label: "4723 - Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados" },
        { value: "4724", label: "4724 - Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados" },
        { value: "4729", label: "4729 - Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados" },
        { value: "4731", label: "4731 - Comercio al por menor de combustible para automotores" },
        { value: "4732", label: "4732 - Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores" },
        { value: "4741", label: "4741 - Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados" },
        { value: "4742", label: "4742 - Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados" },
        { value: "4751", label: "4751 - Comercio al por menor de productos textiles en establecimientos especializados" },
        { value: "4752", label: "4752 - Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados" },
        { value: "4753", label: "4753 - Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados" },
        { value: "4754", label: "4754 - Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación" },
        { value: "4755", label: "4755 - Comercio al por menor de artículos y utensilios de uso doméstico" },
        { value: "4759", label: "4759 - Comercio al por menor de otros artículos domésticos en establecimientos especializados" },
        { value: "4761", label: "4761 - Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados" },
        { value: "4762", label: "4762 - Comercio al por menor de artículos deportivos, en establecimientos especializados" },
        { value: "4769", label: "4769 - Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados" },
        { value: "4771", label: "4771 - Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados" },
        { value: "4772", label: "4772 - Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados" },
        { value: "4773", label: "4773 - Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados" },
        { value: "4774", label: "4774 - Comercio al por menor de otros productos nuevos en establecimientos especializados" },
        { value: "4775", label: "4775 - Comercio al por menor de artículos de segunda mano" },
        { value: "4781", label: "4781 - Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles" },
        { value: "4782", label: "4782 - Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles" },
        { value: "4789", label: "4789 - Comercio al por menor de otros productos en puestos de venta móviles" },
        { value: "4791", label: "4791 - Comercio al por menor realizado a través de Internet" },
        { value: "4792", label: "4792 - Comercio al por menor realizado a través de casas de venta o por correo" },
        { value: "4799", label: "4799 - Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados" },
        { value: "4911", label: "4911 - Transporte férreo de pasajeros" },
        { value: "4912", label: "4912 - Transporte férreo de carga" },
        { value: "4921", label: "4921 - Transporte de pasajeros" },
        { value: "4922", label: "4922 - Transporte mixto" },
        { value: "4923", label: "4923 - Transporte de carga por carretera" },
        { value: "4930", label: "4930 - Transporte por tuberías" },
        { value: "5011", label: "5011 - Transporte de pasajeros marítimo y de cabotaje" },
        { value: "5012", label: "5012 - Transporte de carga marítimo y de cabotaje" },
        { value: "5021", label: "5021 - Transporte fluvial de pasajeros" },
        { value: "5022", label: "5022 - Transporte fluvial de carga" },
        { value: "5111", label: "5111 - Transporte aéreo nacional de pasajeros" },
        { value: "5112", label: "5112 - Transporte aéreo internacional de pasajeros" },
        { value: "5121", label: "5121 - Transporte aéreo nacional de carga" },
        { value: "5122", label: "5122 - Transporte aéreo internacional de carga" },
        { value: "5210", label: "5210 - Almacenamiento y depósito" },
        { value: "5221", label: "5221 - Actividades de estaciones, vías y servicios complementarios para el transporte terrestre" },
        { value: "5222", label: "5222 - Actividades de puertos y servicios complementarios para el transporte acuático" },
        { value: "5223", label: "5223 - Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo" },
        { value: "5224", label: "5224 - Manipulación de carga" },
        { value: "5229", label: "5229 - Otras actividades complementarias al transporte" },
        { value: "5310", label: "5310 - Actividades postales nacionales" },
        { value: "5320", label: "5320 - Actividades de mensajería" },
        { value: "5511", label: "5511 - Alojamiento en hoteles" },
        { value: "5512", label: "5512 - Alojamiento en apartahoteles" },
        { value: "5513", label: "5513 - Alojamiento en centros vacacionales" },
        { value: "5514", label: "5514 - Alojamiento rural" },
        { value: "5519", label: "5519 - Otros tipos de alojamientos para visitantes" },
        { value: "5520", label: "5520 - Actividades de zonas de camping y parques para vehículos recreacionales" },
        { value: "5530", label: "5530 - Servicio por horas" },
        { value: "5590", label: "5590 - Otros tipos de alojamiento n.c.p." },
        { value: "5611", label: "5611 - Expendio a la mesa de comidas preparadas" },
        { value: "5612", label: "5612 - Expendio por autoservicio de comidas preparadas" },
        { value: "5613", label: "5613 - Expendio de comidas preparadas en cafeterías" },
        { value: "5619", label: "5619 - Otros tipos de expendio de comidas preparadas n.c.p." },
        { value: "5621", label: "5621 - Catering para eventos" },
        { value: "5629", label: "5629 - Actividades de otros servicios de comidas" },
        { value: "5630", label: "5630 - Expendio de bebidas alcohólicas para el consumo dentro del establecimiento" },
        { value: "5811", label: "5811 - Edición de libros" },
        { value: "5812", label: "5812 - Edición de directorios y listas de correo" },
        { value: "5813", label: "5813 - Edición de periódicos, revistas y otras publicaciones periódicas" },
        { value: "5819", label: "5819 - Otros trabajos de edición" },
        { value: "5820", label: "5820 - Edición de programas de informática (software)" },
        { value: "5911", label: "5911 - Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión" },
        { value: "5912", label: "5912 - Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión" },
        { value: "5913", label: "5913 - Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión" },
        { value: "5914", label: "5914 - Actividades de exhibición de películas cinematográficas y videos" },
        { value: "5920", label: "5920 - Actividades de grabación de sonido y edición de música" },
        { value: "6010", label: "6010 - Actividades de programación y transmisión en el servicio de radiodifusión sonora" },
        { value: "6020", label: "6020 - Actividades de programación y transmisión de televisión" },
        { value: "6110", label: "6110 - Actividades de telecomunicaciones alámbricas" },
        { value: "6120", label: "6120 - Actividades de telecomunicaciones inalámbricas" },
        { value: "6130", label: "6130 - Actividades de telecomunicación satelital" },
        { value: "6190", label: "6190 - Otras actividades de telecomunicaciones" },
        { value: "6201", label: "6201 - Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)" },
        { value: "6202", label: "6202 - Actividades de consultoría informática y actividades de administración de instalaciones informáticas" },
        { value: "6209", label: "6209 - Otras actividades de tecnologías de información y actividades de servicios informáticos" },
        { value: "6311", label: "6311 - Procesamiento de datos, alojamiento (hosting) y actividades relacionadas" },
        { value: "6312", label: "6312 - Portales web" },
        { value: "6391", label: "6391 - Actividades de agencias de noticias" },
        { value: "6399", label: "6399 - Otras actividades de servicio de información n.c.p." },
        { value: "6411", label: "6411 - Banco Central" },
        { value: "6412", label: "6412 - Bancos comerciales" },
        { value: "6421", label: "6421 - Actividades de las corporaciones financieras" },
        { value: "6422", label: "6422 - Actividades de las compañías de financiamiento" },
        { value: "6423", label: "6423 - Banca de segundo piso" },
        { value: "6424", label: "6424 - Actividades de las cooperativas financieras" },
        { value: "6431", label: "6431 - Fideicomisos, fondos y entidades financieras similares" },
        { value: "6432", label: "6432 - Fondos de cesantías" },
        { value: "6491", label: "6491 - Leasing financiero (arrendamiento financiero)" },
        { value: "6492", label: "6492 - Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario" },
        { value: "6493", label: "6493 - Actividades de compra de cartera o factoring" },
        { value: "6494", label: "6494 - Otras actividades de distribución de fondos" },
        { value: "6495", label: "6495 - Instituciones especiales oficiales" },
        { value: "6499", label: "6499 - Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p." },
        { value: "6511", label: "6511 - Seguros generales" },
        { value: "6512", label: "6512 - Seguros de vida" },
        { value: "6513", label: "6513 - Reaseguros" },
        { value: "6514", label: "6514 - Capitalización" },
        { value: "6521", label: "6521 - Servicios de seguros sociales de salud" },
        { value: "6522", label: "6522 - Servicios de seguros sociales de riesgos profesionales" },
        { value: "6531", label: "6531 - Régimen de prima media con prestación definida (RPM)" },
        { value: "6532", label: "6532 - Régimen de ahorro individual (RAI)" },
        { value: "6611", label: "6611 - Administración de mercados financieros" },
        { value: "6612", label: "6612 - Corretaje de valores y de contratos de productos básicos" },
        { value: "6613", label: "6613 - Otras actividades relacionadas con el mercado de valores" },
        { value: "6614", label: "6614 - Actividades de las casas de cambio" },
        { value: "6615", label: "6615 - Actividades de los profesionales de compra y venta de divisas" },
        { value: "6619", label: "6619 - Otras actividades auxiliares de las actividades de servicios financieros n.c.p." },
        { value: "6621", label: "6621 - Actividades de agentes y corredores de seguros" },
        { value: "6629", label: "6629 - Evaluación de riesgos y daños, y otras actividades de servicios auxiliares" },
        { value: "6630", label: "6630 - Actividades de administración de fondos" },
        { value: "6810", label: "6810 - Actividades inmobiliarias realizadas con bienes propios o arrendados" },
        { value: "6820", label: "6820 - Actividades inmobiliarias realizadas a cambio de una retribución o por contrata" },
        { value: "6910", label: "6910 - Actividades jurídicas" },
        { value: "6920", label: "6920 - Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria" },
        { value: "7010", label: "7010 - Actividades de administración empresarial" },
        { value: "7020", label: "7020 - Actividades de consultaría de gestión" },
        { value: "7110", label: "7110 - Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica" },
        { value: "7120", label: "7120 - Ensayos y análisis técnicos" },
        { value: "7210", label: "7210 - Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería" },
        { value: "7220", label: "7220 - Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades" },
        { value: "7310", label: "7310 - Publicidad" },
        { value: "7320", label: "7320 - Estudios de mercado y realización de encuestas de opinión pública" },
        { value: "7410", label: "7410 - Actividades especializadas de diseño" },
        { value: "7420", label: "7420 - Actividades de fotografía" },
        { value: "7490", label: "7490 - Otras actividades profesionales, científicas y técnicas n.c.p." },
        { value: "7500", label: "7500 - Actividades veterinarias" },
        { value: "7710", label: "7710 - Alquiler y arrendamiento de vehículos automotores" },
        { value: "7721", label: "7721 - Alquiler y arrendamiento de equipo recreativo y deportivo" },
        { value: "7722", label: "7722 - Alquiler de videos y discos" },
        { value: "7729", label: "7729 - Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p." },
        { value: "7730", label: "7730 - Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p." },
        { value: "7740", label: "7740 - Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor" },
        { value: "7810", label: "7810 - Actividades de agencias de empleo" },
        { value: "7820", label: "7820 - Actividades de agencias de empleo temporal" },
        { value: "7830", label: "7830 - Otras actividades de suministro de recurso humano" },
        { value: "7911", label: "7911 - Actividades de las agencias de viaje" },
        { value: "7912", label: "7912 - Actividades de operadores turísticos" },
        { value: "7990", label: "7990 - Otros servicios de reserva y actividades relacionadas" },
        { value: "8010", label: "8010 - Actividades de seguridad privada" },
        { value: "8020", label: "8020 - Actividades de servicios de sistemas de seguridad" },
        { value: "8030", label: "8030 - Actividades de detectives e investigadores privados" },
        { value: "8110", label: "8110 - Actividades combinadas de apoyo a instalaciones" },
        { value: "8121", label: "8121 - Limpieza general interior de edificios" },
        { value: "8129", label: "8129 - Otras actividades de limpieza de edificios e instalaciones industriales" },
        { value: "8130", label: "8130 - Actividades de paisajismo y servicios de mantenimiento conexos" },
        { value: "8211", label: "8211 - Actividades combinadas de servicios administrativos de oficina" },
        { value: "8219", label: "8219 - Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina" },
        { value: "8220", label: "8220 - Actividades de centros de llamadas (Call center)" },
        { value: "8230", label: "8230 - Organización de convenciones y eventos comerciales" },
        { value: "8291", label: "8291 - Actividades de agencias de cobranza y oficinas de calificación crediticia" },
        { value: "8292", label: "8292 - Actividades de envase y empaque" },
        { value: "8299", label: "8299 - Otras actividades de servicio de apoyo a las empresas n.c.p." },
        { value: "8411", label: "8411 - Actividades legislativas de la administración pública" },
        { value: "8412", label: "8412 - Actividades ejecutivas de la administración pública" },
        { value: "8413", label: "8413 - Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social" },
        { value: "8414", label: "8414 - Actividades reguladoras y facilitadoras de la actividad económica" },
        { value: "8415", label: "8415 - Actividades de los otros órganos de control" },
        { value: "8421", label: "8421 - Relaciones exteriores" },
        { value: "8422", label: "8422 - Actividades de defensa" },
        { value: "8423", label: "8423 - Orden público y actividades de seguridad" },
        { value: "8424", label: "8424 - Administración de justicia" },
        { value: "8430", label: "8430 - Actividades de planes de seguridad social de afiliación obligatoria" },
        { value: "8511", label: "8511 - Educación de la primera infancia" },
        { value: "8512", label: "8512 - Educación preescolar" },
        { value: "8513", label: "8513 - Educación básica primaria" },
        { value: "8521", label: "8521 - Educación básica secundaria" },
        { value: "8522", label: "8522 - Educación media académica" },
        { value: "8523", label: "8523 - Educación media técnica y de formación laboral" },
        { value: "8530", label: "8530 - Establecimientos que combinan diferentes niveles de educación" },
        { value: "8541", label: "8541 - Educación técnica profesional" },
        { value: "8542", label: "8542 - Educación tecnológica" },
        { value: "8543", label: "8543 - Educación de instituciones universitarias o de escuelas tecnológicas" },
        { value: "8544", label: "8544 - Educación de universidades" },
        { value: "8551", label: "8551 - Formación académica no formal" },
        { value: "8552", label: "8552 - Enseñanza deportiva y recreativa" },
        { value: "8553", label: "8553 - Enseñanza cultural" },
        { value: "8559", label: "8559 - Otros tipos de educación n.c.p." },
        { value: "8560", label: "8560 - Actividades de apoyo a la educación" },
        { value: "8610", label: "8610 - Actividades de hospitales y clínicas, con internación" },
        { value: "8621", label: "8621 - Actividades de la práctica médica, sin internación" },
        { value: "8622", label: "8622 - Actividades de la práctica odontológica" },
        { value: "8691", label: "8691 - Actividades de apoyo diagnóstico" },
        { value: "8692", label: "8692 - Actividades de apoyo terapéutico" },
        { value: "8699", label: "8699 - Otras actividades de atención de la salud humana" },
        { value: "8710", label: "8710 - Actividades de atención residencial medicalizada de tipo general" },
        { value: "8720", label: "8720 - Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas" },
        { value: "8730", label: "8730 - Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas" },
        { value: "8790", label: "8790 - Otras actividades de atención en instituciones con alojamiento" },
        { value: "8810", label: "8810 - Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas" },
        { value: "8890", label: "8890 - Otras actividades de asistencia social sin alojamiento" },
        { value: "9001", label: "9001 - Creación literaria" },
        { value: "9002", label: "9002 - Creación musical" },
        { value: "9003", label: "9003 - Creación teatral" },
        { value: "9004", label: "9004 - Creación audiovisual" },
        { value: "9005", label: "9005 - Artes plásticas y visuales" },
        { value: "9006", label: "9006 - Actividades teatrales" },
        { value: "9007", label: "9007 - Actividades de espectáculos musicales en vivo" },
        { value: "9008", label: "9008 - Otras actividades de espectáculos en vivo" },
        { value: "9101", label: "9101 - Actividades de bibliotecas y archivos" },
        { value: "9102", label: "9102 - Actividades y funcionamiento de museos, conservación de edificios y sitios históricos" },
        { value: "9103", label: "9103 - Actividades de jardines botánicos, zoológicos y reservas naturales" },
        { value: "9200", label: "9200 - Actividades de juegos de azar y apuestas" },
        { value: "9311", label: "9311 - Gestión de instalaciones deportivas" },
        { value: "9312", label: "9312 - Actividades de clubes deportivos" },
        { value: "9319", label: "9319 - Otras actividades deportivas" },
        { value: "9321", label: "9321 - Actividades de parques de atracciones y parques temáticos" },
        { value: "9329", label: "9329 - Otras actividades recreativas y de esparcimiento n.c.p." },
        { value: "9411", label: "9411 - Actividades de asociaciones empresariales y de empleadores" },
        { value: "9412", label: "9412 - Actividades de asociaciones profesionales" },
        { value: "9420", label: "9420 - Actividades de sindicatos de empleados" },
        { value: "9491", label: "9491 - Actividades de asociaciones religiosas" },
        { value: "9492", label: "9492 - Actividades de asociaciones políticas" },
        { value: "9499", label: "9499 - Actividades de otras asociaciones n.c.p." },
        { value: "9511", label: "9511 - Mantenimiento y reparación de computadores y de equipo periférico" },
        { value: "9512", label: "9512 - Mantenimiento y reparación de equipos de comunicación" },
        { value: "9521", label: "9521 - Mantenimiento y reparación de aparatos electrónicos de consumo" },
        { value: "9522", label: "9522 - Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería" },
        { value: "9523", label: "9523 - Reparación de calzado y artículos de cuero" },
        { value: "9524", label: "9524 - Reparación de muebles y accesorios para el hogar" },
        { value: "9529", label: "9529 - Mantenimiento y reparación de otros efectos personales y enseres domésticos" },
        { value: "9601", label: "9601 - Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel" },
        { value: "9602", label: "9602 - Peluquería y otros tratamientos de belleza" },
        { value: "9603", label: "9603 - Pompas fúnebres y actividades relacionadas" },
        { value: "9609", label: "9609 - Otras actividades de servicios personales n.c.p." },
        { value: "9700", label: "9700 - Actividades de los hogares individuales como empleadores de personal doméstico" },
        { value: "9810", label: "9810 - Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio" },
        { value: "9820", label: "9820 - Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio" },
        { value: "9900", label: "9900 - Actividades de organizaciones y entidades extraterritoriales" },
    ];

    const customFilterOption = ({ label, data }: any, string: string) => {
        const labelLower = label.toLowerCase();
        const stringLower = string.toLowerCase();
        const value = data.value.toLowerCase();
        const labelContainsString = labelLower.includes(stringLower);
        const valueContainsString = value.includes(stringLower);
        return labelContainsString || valueContainsString;
    };

    return (
        <div className={`${styles.container} mb-4 d-flex align-items-center justify-content-center gap-3 w-100`}>
            <div className={`${styles.container__Info} d-flex flex-column align-items-start justify-content-start position-relative`}>
                <h6 className={styles.label}><span className={`${styles.required__Information} `}>*</span> Selecciona un código CIIU</h6>
                <div className={styles.container__Input}>
                    <Select
                        className={`${styles.input} border-0`}
                        options={codesCiiu}
                        value={codeCiiu}
                        onChange={handleCiiuCodeChange}
                        filterOption={customFilterOption}
                    />
                </div>
            </div>
        </div>
    );
};

export default CodesCiiu;